all: magic

magic: magic.c  parseInput.c isMagicBox.c printErrMsg.c printMatrix.c  data.h
	gcc -ansi -Wall -pedantic  magic.c  parseInput.c isMagicBox.c printErrMsg.c printMatrix.c -o magic

clean: rm *~
