PrintSpecialChars: PrintSpecialChars.o
	gcc -ansi -Wall -g PrintSpecialChars.o -o PrintSpecialChars
PrintSpecialChars.o: PrintSpecialChars.c
	gcc -c -ansi -Wall -g PrintSpecialChars.c -o PrintSpecialChars.o
