SpecialCharCounter: SpecialCharCounter.o
	gcc -ansi -Wall -g SpecialCharCounter.o -o SpecialCharCounter
SpecialCharCounter.o: SpecialCharCounter.c
	gcc -c -ansi -Wall -g SpecialCharCounter.c -o SpecialCharCounter.o
