tester: main.o lower.o
	gcc -ansi -pedantic -Wall -g main.o lower.o -o tester
lower.o: lower.c
	gcc -c -ansi -pedantic -Wall -g lower.c -o lower.o
main.o: main.c
	gcc -c -ansi -pedantic -Wall -g main.c -o main.o
