CharFrequencies: CharFrequencies.o
	gcc -ansi -pedantic -Wall -g CharFrequencies.o -o CharFrequencies
CharFrequencies.o: CharFrequencies.c
	gcc -c -ansi -pedantic -Wall -g CharFrequencies.c -o CharFrequencies.o
