WordLengthHistogram: WordLengthHistogram.o
	gcc -ansi -pedantic -Wall -g WordLengthHistogram.o -o WordLengthHistogram
WordLengthHistogram.o: WordLengthHistogram.c
	gcc -c -ansi -pedantic -Wall -g WordLengthHistogram.c -o WordLengthHistogram.o
