tester: main.o bitcount.o
	gcc -ansi -pedantic -Wall -g main.o bitcount.o -o tester
bitcount.o: bitcount.c
	gcc -c -ansi -pedantic -Wall -g bitcount.c -o bitcount.o
main.o: main.c
	gcc -c -ansi -pedantic -Wall -g main.c -o main.o
