bitOps: main.o functions.o
	gcc -ansi -pedantic -Wall -g main.o functions.o -o bitOps
functions.o: functions.c
	gcc -c -ansi -pedantic -Wall -g functions.c -o functions.o
main.o: main.c
	gcc -c -ansi -pedantic -Wall -g main.c -o main.o
