reverseTempConversion: reverseTempConversion.o
	gcc -ansi -Wall -g reverseTempConversion.o -o reverseTempConversion
reverseTempConversion.o: reverseTempConversion.c data.h
	gcc -c -ansi -Wall -g reverseTempConversion.c -o reverseTempConversion.o
